;
; Driver Installer Section (For DrvInst)
;
; Copyright (c) 2007-2014 RICOH COMPANY, LTD
; All Rights Reserved
;

[DrvInst]
DrvInst=Gestetner MP C4501 PCL 6,Gestetner MP C5501 PCL 6,Gestetner MP C4501A PCL 6,Gestetner MP C5501A PCL 6,infotec MP C4501 PCL 6,infotec MP C5501 PCL 6,infotec MP C4501A PCL 6,infotec MP C5501A PCL 6,LANIER MP C4501/LD645C PCL 6,LANIER MP C5501/LD655C PCL 6,LANIER MPC4501A/LD645CA PCL 6,LANIER MPC5501A/LD655CA PCL 6,NRG MP C4501 PCL 6,NRG MP C5501 PCL 6,NRG MP C4501A PCL 6,NRG MP C5501A PCL 6,RICOH Aficio MP C4501 PCL 6,RICOH Aficio MP C5501 PCL 6,RICOH Aficio MP C4501A PCL 6,RICOH Aficio MP C5501A PCL 6,SAVIN C9145 PCL 6,SAVIN C9155 PCL 6,SAVIN C9145A PCL 6,SAVIN C9155A PCL 6
Comment="PCL 6 Driver (Windows 2000 or later)"
VendorSetup=
NoCheckFiles=
DriverType=PCL6
Version=3
IniFileName=RPCL.ini,allusers
ScenarioInstallOK=ON
RConfigFileOSVersion=3
DriverVersion=1.5.0.0
IniFileSupport=3
RCFFormatVersion=1.0
RCFHandling=1
UserCodeOK=ON
Platform=NTamd64
